### ISSUE TITLE
Future plans for Thinny

### ISSUE THREAD

**Issue by ianbrunelli** [camporez/Thinny#23]
![Dolores](http://i.imgur.com/ELmnoJE.jpg)

Hello, everybody!

I'm about to start working again on Thinny 2.2, and I'd like to know what do you think we could do for this version.

I'm currently planning to add share functionality and rework the Parallax effect (use another library), but I think this next version needs something more. What do you guys think could be added/changed/reworked?

Also, I'm opening the issue tracker on this page and closing the old one, since I'm planning to delete that repo soon. Here is a relevant list of proposed features in there:

- support for twitter cards and open graph, by @maxheld83

- Close menu when click on page, by @bryanjhv

- colored buttons, by @maxheld83

- A guide for Thinny, by @zenstealth

- Add a button to share the post on social networks, by me

Tagging the people who made pull requests cause they may be interested in this: @jamchamb @hyjk2000 @bgiesing @10by10pixel @Aryess @aguslr @MarcosX @goodev @Kristories @EmilS @mence (thank you all!).

**Comment by bgiesing** [comment]
@ianbrunelli Glad I could help!

**Comment by hyjk2000** [comment]
@ianbrunelli I'm happy to help. About new features, I suggest an auto generating TOC. I added one  on [my blog](https://hyjk2000.github.io/2014/01/23/arch-linux-install-guide/) but is pretty buggy when scrolling. The [sticky-float plugin](https://github.com/hyjk2000/jquery.sticky-float) seem to be conflicting with the Parallax effect.

**Comment by ianbrunelli** [comment]
@hyjk2000 That looks good (except for the Parallax conflict)!

About the Parallax, I'm planning to redo all of it using a different library.

Also, it doesn't look good on mobile (the sticky-float plugin). But it's surely something I'd like to implement.

P.S.: Recently I added a variable to disable the Parallax effect.

**Comment by Aryess** [comment]
@ianbrunelli You're welcome. 
My main beef with Thinny is the the popup menu. Not very pratical (takes two clicks to go anywhere), and looks a bit odd on this design anyway. Everything is very flat, very simple, and then you have this black block that really stands out. Maybe something like this would go better?
![capture d ecran de 2015-02-09 09 09 12](https://cloud.githubusercontent.com/assets/3518172/6103362/560f5924-b03b-11e4-9aa2-b98767355226.png)
Still not fully statisfied, but it blends a bit better I think. (Added a bit of dummy text to see how it would scale)

**Comment by ianbrunelli** [comment]
@Aryess You have a good point. But with the menu items always visible we can't make the menu always visible on the page, so you'd still have two steps before opening some item (go back to the top and then click the item).

About the current design, I don't like the black box either, but it was the only way I could think of to make the menu visible in both dark and clean backgrounds. I've another idea now, will see if it works.

**Comment by ianbrunelli** [comment]
Guys, you can now see the changes on the `dev` branch in action.

Here's a post about 2.2: [A quick look into Thinny 2.2](http://thinny.github.io/blog/a-quick-look-into-thinny-22/)

I think the new Parallax implementation will arrive just in 2.3. :disappointed: 

Any comment about the menu and everything else?

**Comment by bgiesing** [comment]
@ianbrunelli Applied it to my site and noticed the theme color's I choose conflicted either being too light or too dark for the links. Any idea other than changing colors?
![color-1](https://cloud.githubusercontent.com/assets/7895463/6117313/2822de12-b079-11e4-9ee3-ab0cc18d4002.png)
![color-2](https://cloud.githubusercontent.com/assets/7895463/6117311/282243f8-b079-11e4-866d-6fa77a48fd02.png)
![color-3](https://cloud.githubusercontent.com/assets/7895463/6117312/28229010-b079-11e4-8a2d-39f05d979d33.png)

**Comment by Kristories** [comment]
![](https://dl.dropboxusercontent.com/u/83581209/github/camporez%3AThinny/Screen%20Shot%202015-02-10%20at%205.30.35%20AM.png)

![](https://dl.dropboxusercontent.com/u/83581209/github/camporez%3AThinny/Screen%20Shot%202015-02-10%20at%205.31.34%20AM.png)

I think would be better if *social* and *share* exchanged.

**Comment by ianbrunelli** [comment]
@bgiesing No :/

Maybe I can add a variable to disable using the `color` variable on text, or you can manually change the `highlight` variable on the `style.sass` file...

@Kristories I thought it would be better to have the share buttons always acessible, but I agree that it would bring more consistency between the mobile and desktop styles.

Any idea on how I can put the top right in a way that its purpose is clear and it won't be confused with social links? I mean, other than putting a "Share" text, because it would make it a bit cluttered.

**Comment by Kristories** [comment]
@ianbrunelli how about share link count?

**Comment by ianbrunelli** [comment]
@Kristories You mean something like this?

![share](http://www.designspot.com.ba/wp-content/uploads/2014/07/addthis.png)

I don't know if it can be done with a custom stylesheet. This default style will look awful with Thinny.

**Comment by bgiesing** [comment]
@ianbrunelli maybe add a second menu using a share icon that expands to show the share icons like it is currently.

**Comment by ianbrunelli** [comment]
@bgiesing One menu on each side of the screen, and both of them fixed?

**Comment by Kristories** [comment]
@ianbrunelli Yes, but with Thinny style :rocket: 

Eg [Facebook count shares](http://graph.facebook.com/http://thinny.github.io/blog/a-quick-look-into-thinny-22)

**Comment by ianbrunelli** [comment]
@Kristories Okay, that seems a bit complicated and heavy, because I'd have to get counts for five social networks... Also, I'm not a fan of shares counter myself.

But I've to agree it is a good way to make the social and share icons visually distinguishable.

**Comment by bgiesing** [comment]
@ianbrunelli Exactly, one menu would be the current one with the hamburger icon for navigation and a new second one would have a sharing symbol (think Android/iOS share icons) and would have the share buttons in them. The nav menu could still scroll down the page with you but the share menu would be fixed to the cover image.

**Comment by ianbrunelli** [comment]
Some thoughts about the menu, the share buttons and the social links:

- The share icon should be always visible on a post. Imagine you're a user and you finish reading a post, the share icon should be there to remember you of sharing it with your friends.

- I'm not sure about the menu... Maybe turn it into a "←" button inside the page/post (fixed on the header) and display a full menu on the index page (like @Aryess' mockup, but without the dark background) is a nice idea. On mobile, it would stay the way it is now.

- The social links would be visible just on the index page. Top right on desktop, and inside the menu on mobile, just like the way it is now.

My main concern here is to keep everything uncluttered. What do you think about this proposal?

**Comment by bgiesing** [comment]
@ianbrunelli I think that it sounds great!

**Comment by ianbrunelli** [comment]
Great!

I hope I can get it done today :D

**Comment by ianbrunelli** [comment]
Okay, gentlemen.

This is how the index page looks like on desktop (the menu looks weird on the left, so I had to put it on right, and the social icons also looks weird on the left, that's why it's now above the site icon):

![captura de tela de 2015-02-10 14 30 08](https://cloud.githubusercontent.com/assets/5755892/6131160/1d195a24-b131-11e4-8aca-b8a97e560293.png)

And this is the post page. This share icon is the only one on Genericons, maybe I will change it...

![captura de tela de 2015-02-10 14 31 01](https://cloud.githubusercontent.com/assets/5755892/6131187/52883b80-b131-11e4-92ad-e9b42f64d938.png)

**Comment by bgiesing** [comment]
@ianbrunelli Looks amazing!

**Comment by ianbrunelli** [comment]
A preview is now available on the test blog (http://thinny.github.io/).

I still have to work on the share stylesheet to give a good look to it.

What do you think? :smiley:

**Comment by bgiesing** [comment]
@ianbrunelli The Share pop-up is not padded on Yandex:
![thinny-yandex-v3](https://cloud.githubusercontent.com/assets/7895463/6137098/ca72b058-b13b-11e4-9f19-f755c47c0c27.png)

**Comment by ianbrunelli** [comment]
Sorry, @bgiesing. Fixed it! :smile:

**Comment by bgiesing** [comment]
@ianbrunelli I'll just leave this here:
![thinny-yandex-v4](https://cloud.githubusercontent.com/assets/7895463/6138619/51405c28-b148-11e4-894f-f61722a9efe1.png)

**Comment by ianbrunelli** [comment]
Done. God, forgive me for coding this ugly workaround (two identical icons), but it's a needed evil.

It's hard to support this API without the browser installed, please keep giving me feedback.

Also, I enabled the Parallax effect again, it looks more stable after some code cleanup.

I need to fix the issue with the site icon. Please let me know of any other issue.

**Comment by bgiesing** [comment]
@ianbrunelli 404 page is broken beyond repair:
![thinny-404-v1](https://cloud.githubusercontent.com/assets/7895463/6139136/d8762be6-b14d-11e4-952a-8e6afc242dc1.png)

**Comment by ianbrunelli** [comment]
Nooooooooooooooooooooooooooooooo!

I've disabled the menu and social links on fullscreen pages.

**Comment by bgiesing** [comment]
@ianbrunelli That was the last thing I found... so far.

**Comment by ianbrunelli** [comment]
@bgiesing Well, now I just found out all the blockquote style stopped working and I've to clue why :stuck_out_tongue: 

Also, is the popup arrow still messy in there?

**Comment by bgiesing** [comment]
@ianbrunelli The arrow looks fine to me!

**Comment by ianbrunelli** [comment]
@bgiesing Awesome!

Now I just have to fix the issue with the site icon and the Parallax effect, and then I'm planning to release it.

I hope I can do this tonight, because tomorrow I have some TV shows to watch and a book to finish :stuck_out_tongue_closed_eyes:

**Comment by bgiesing** [comment]
What happened to the dev branch? @ianbrunelli

**Comment by ianbrunelli** [comment]
@bgiesing It was moved to a new repository, because I was changing lots of things and then I realized it was becoming almost a new theme.

The thing is, I really want to make something professional this time, so I thought it would be better this way.

I'm not sure yet about the future it will have, if I'll move it to here or give it a new name/repo.
