### ISSUE TITLE
Add Support for Yandex.Browser Alpha's Transparency API

### ISSUE THREAD

**Issue by bgiesing** [camporez/Thinny#24]
Yandex introduced a [new browser](http://browser.yandex.com/future) that makes websites more like apps by reducing chrome and coloring the browser based on the website.

I propose that you integrate their [Transparency Mode API](http://api.yandex.com/transparency/) which allows you to either:
- Make the browser fully transparent
- Add color to the browser.

I suggest that if you choose to use color instead of transparency, that you use the theme_color variable I added in an older pull request so the color matches.

But if you do transparency, you will have to [check that the browser supports it](http://api.yandex.com/transparency/doc/dg/concepts/checking.xml) so you can add padding so elements are not behind the browser's chrome.

Finally, here are some pictures (the first uses color and second uses transparency):
![Facebook](http://api.yandex.com/transparency/freeze/5EfSY8m_Ep4O_RgvPI_frzS0Z0w.png)
![Maps](http://api.yandex.com/transparency/freeze/H1iFhPOjpJIgUq7VEP5SPhnp6po.png)

@ianbrunelli

**Comment by bgiesing** [comment]
@ianbrunelli I tried implementing the transparency myself, but I don't know much about CSS so I couldn't add the padding.

**Comment by ianbrunelli** [comment]
I think I can do this, but the browser isn't available for Linux.

Would you be available to test dev branch and send me screenshots while I'm implementing it?

**Comment by bgiesing** [comment]
@ianbrunelli Sure!

**Comment by ianbrunelli** [comment]
Okay, I'll start the work :smiley:

**Comment by ianbrunelli** [comment]
Just pushed to [dev](https://github.com/camporez/Thinny/tree/dev). Could you try it and tell if it works?

I think it won't, because it was too easy, but let me know if I'm on the right path or not :stuck_out_tongue_closed_eyes:

**Comment by bgiesing** [comment]
Same result I had, it is transparent but no padding. Also, the black text I learned is currently a browser bug, it will be fixed later on so don't worry about not being able to read the text.

![thinny-yandex-v1](https://cloud.githubusercontent.com/assets/7895463/6094416/dcf3f218-aeee-11e4-83a0-4a7156686ab9.png)

**Comment by ianbrunelli** [comment]
Okay... I think I know what I'll have to do.

**Comment by ianbrunelli** [comment]
I don't changed much.... Their API isn't too clear, and there isn't much info on Google.

Could you please try again?

**Comment by bgiesing** [comment]
Exact same...

**Comment by ianbrunelli** [comment]
Okay, now I'm doing **exactly** how they do on Yandex.Maps, if it doesn't work I don't know what will.

**Comment by bgiesing** [comment]
Still doesn't work, but I found a website with a [tutorial](https://dikmax.name/post/yandex-browser/). Maybe it will help? (NOTE: TRANSLATE SITE)

![Site](https://dikmax.name/images/screenshots/yandex-browser-blog.png)

**Comment by ianbrunelli** [comment]
Okay, I don't know why this is working now that I changed "true" to "false", but it's working...

Could you try it again?

**Comment by bgiesing** [comment]
We have lift off!

![thinny-yandex-v2](https://cloud.githubusercontent.com/assets/7895463/6094698/acc369ea-aefb-11e4-9522-f20551fdec28.png)

**Comment by ianbrunelli** [comment]
\o/

Now, two things:

1. Are you sure the black text and buttons are something they will change (and I won't have to add something to the HTML)?

2. Do you have any idea on how they are setting that blue color for the that (and if I can add something to change that)?

**Comment by bgiesing** [comment]
@ianbrunelli 

1. [Read 2nd question here](http://help.yandex.com/newbrowser/faq/faq-common.xml)
2. I am not sure but I think you have to use the [Tableau API](http://api.yandex.com/tableau/)

**Comment by ianbrunelli** [comment]
Thanks, I'll take a look at the Tableau API later.

I'm closing the issue and hoping they solve the scrollbar problem before they release a Linux version of it :P 

Thank you, it was something fun to add!

**Comment by bgiesing** [comment]
@ianbrunelli Just noticed a couple of problems:

1. Social links are not aligned with menu. Menu has a padding of 44px and Social has a padding of 32px. This looks awkward.
2. Social is also checking for `ya-dock-fade` instead of `ya-title-fade`. Works the same without the change but you never know.

**Comment by ianbrunelli** [comment]
1. That's because social icons must be aligned with the icon *inside* the menu, not the button itself...

2. Yeah, I've changed this earlier today but isn't pushed yet. In fact, I've grouped all the Yandex.Browser specific code inside two `@media` checks.

**Comment by ianbrunelli** [comment]
You we're right, the damn thing wasn't perfectly aligned (not just on Yandex). Now it is exactly between the menu background and the icon.

24px for the menu icon, 30px for the social buttons, 36px for the menu.

![Boundaries](http://i.imgur.com/t7AxR5y.jpg)

**Comment by bgiesing** [comment]
@ianbrunelli Can you push it up for me to test?

**Comment by ianbrunelli** [comment]
Sure :)

**Comment by bgiesing** [comment]
@ianbrunelli Working fine! :smile:

**Comment by bgiesing** [comment]
@ianbrunelli Before you publish to master, you might want to rebase though... Commit's are a little messy.

**Comment by ianbrunelli** [comment]
It will be a while before I publish it to master. I still have to cleanup the code (mainly the CSS now) and work on the new parallax implementation...

**Comment by bgiesing** [comment]
@ianbrunelli Well to clean up the CSS even more couldn't you for the Yandex entries:

```css
@media (ya-title-fade: false), (ya-title-fade: true) and (ya-dock-fade: false), (ya-dock-fade: true) {
	#img-info {
		bottom: 47px;
	}

	.nav-icon-top {
		bottom: 62px;
	}

	.social {
		top: 52px;
	}

	.menu {
		top: 46px;
	}

	.copyright {
		bottom: 42px;
	}

	.footer-small {
		height: 92px;
	}
}
```

By combining the title and dock entries in one with an and?

**Comment by ianbrunelli** [comment]
Yeap.

But I'll try to do something in a way to make the code easier to read and to maintain (using an unique file for both mobile and desktop styles). Maybe I'll use port it to SASS or LESS.

**Comment by ianbrunelli** [comment]
@bgiesing Just pushed the new stylesheet to `dev`. Could you test it on Yandex to make sure it still works as before?

**Comment by bgiesing** [comment]
@ianbrunelli Works fine!
