### ISSUE TITLE
Footer not sticking to bottom of page

### ISSUE THREAD

**Issue by jamchamb** [camporez/Thinny#28]
When there's not enough content in a page using the "page" layout, the footer doesn't stick to the bottom. I've observed this in Firefox and Chrome on Windows, with Thinny 2.1 and 2.2
![thinny-footer](https://cloud.githubusercontent.com/assets/7306764/6158857/b0e3c6ea-b21c-11e4-841f-de7bec94046d.png)

**Comment by ianbrunelli** [comment]
It also happens in the index page if the number of posts is low.

Thanks for the reminder. I'll try to fix it before 2.2 release.

**Comment by ianbrunelli** [comment]
@jamchamb Could you please just confirm to me if it is okay now?

**Comment by jamchamb** [comment]
The fix is working for Chrome, but not Firefox (v35.0.1).

**Comment by ianbrunelli** [comment]
Confirmed. I'll try a different approach.

**Comment by ianbrunelli** [comment]
Okay, I've found the problem. Not sure if/when I'll fix it on Thinny 2.1, cause it requires more changes than I first thought and I'm busy working on the next version.

I'm closing the issue, though, as it is already implemented for future releases..
