### ISSUE TITLE
Add a .gitignore

### ISSUE THREAD

**Issue by jamchamb** [camporez/Thinny#29]
The standard `.gitignore` for Jekyll contains:
```
_site/
.sass-cache/
```
We should also decide whether to [check in or ignore Gemfile.lock](http://stackoverflow.com/questions/4151495/should-gemfile-lock-be-included-in-gitignore).

**Comment by ianbrunelli** [comment]
I once thought of adding _posts/* to a .gitignore, but I don't know if it should be done.

I'll take a look at this PR and finish what is still missing for 2.2 as soon as I get home next week.

**Comment by jamchamb** [comment]
I wouldn't add `_posts`, as people using GitHub Pages need to commit stuff there. There are other ways to avoid changes in `_posts` getting mixed with development, such as working on a fresh branch or doing a [recursive `--assume-unchanged`](http://stackoverflow.com/questions/12288212/git-update-index-assume-unchanged-on-directory).

**Comment by ianbrunelli** [comment]
Yeah, you're right!

What about turning `_posts` and `media` into submodules?

I'm not sure how would that work for forks. What I want is to make Thinny's "core" independent from the blog's entries and configuration, so one would be able to update versions easily, and also to send pull requests directly from the blog repo.

**Comment by jamchamb** [comment]
I actually just wrote a blog post about how I do that: http://jamchamb.github.io/blog/keeping-jekyll-in-check/

Submodules are generally committed as the commit hash of the sub-repo, so I don't think that would work for uploading posts either. If you want to do all the work in one repo, you could probably create branch copies of the upstream master branch for development and then do something similar to what I describe in the post.

**Comment by ianbrunelli** [comment]
Just added the `.gitignore` file with the stantard entries.

Your blog post is really interesting, maybe I can put it as reference on the README...

Thank you!
