### ISSUE TITLE
Misplaced footer with parallax and disqus turned on

### ISSUE THREAD

**Issue by rurza** [camporez/Thinny#34]
![screen shot 2015-03-25 at 17 13 33](https://cloud.githubusercontent.com/assets/2467137/6829214/4f76e902-d312-11e4-917c-ec6b4eb4c9c5.png)

**Comment by ianbrunelli** [comment]
`stellar.js` is presenting some issues with things disappearing and I tried several times to fix them, but nothing helped and I'd no idea what else to try.

That's one of the reasons why I'm dropping it in favor of a custom script called `jquery.thinny-parallax.js` on the "Next" version.

It may be possible to use it here, but honestly I'm not willing to maintain Thinny 2 in parallel with "Next".

Feel free to work on this if you want and send a pull request here.
