### ISSUE TITLE
Domain Name expired for camporez.com

### ISSUE THREAD

**Issue by dhanvi** [camporez/Thinny#35]
![screenshot from 2015-05-03 22 02 29](https://cloud.githubusercontent.com/assets/6671379/7445816/3050193a-f1e0-11e4-8fcb-5796c71207da.png)

hope you guys renew it soon :+1:

**Comment by ianbrunelli** [comment]
Well, I'm not going to renew the domain. The demo site is still alive on camporez.github.io, I'll change the domain on the README.

**Comment by dhanvi** [comment]
@ianbrunelli also don't forget to change the cname as camporez.github.io is getting redirected to the old expired domain :(
